services:
  infrax:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ELASTICSEARCH_HOST="http://localhost:9200/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
